NDefines_Graphics.NGraphics.UNITS_ICONS_DISTANCE_CUTOFF = 3000
NDefines_Graphics.NGraphics.MAP_ICONS_GROUP_CAM_DISTANCE = 800.0
NDefines_Graphics.NGraphics.MAP_ICONS_STATE_GROUP_CAM_DISTANCE = 850.0
NDefines_Graphics.NGraphics.MAP_ICONS_STRATEGIC_GROUP_CAM_DISTANCE = 900.0
NDefines_Graphics.NGraphics.FRIEND_COLOR  = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.ENEMY_COLOR   = {1.0, 1.0, 1.0}
NDefines_Graphics.NGraphics.NEUTRAL_COLOR = {1.0, 1.0, 1.0}
NDefines.NGraphics.DRAW_REFRACTIONS_CUTOFF = 0
NDefines.NGraphics.SUN_HEIGHT  = 500 -- higher means softer shadows and more intense light
NDefines.NGraphics.SUN_DIFFUSE_COLOR   	= {0.14, 0.14, 1.0}
